# Asynchronous inputs: no timing relationship to any clock
set_false_path -from [get_ports btn_n]
# LCD outputs are generated by a divided fabric strobe, not a clock: no output delay analysis
set_false_path -to [get_ports {lcd_sclk lcd_mosi lcd_cs_n lcd_dcx lcd_resx_n}]

# axis_async_fifo Gray pointer crossings: bound datapath delay to one source clock period so
# consecutive single-bit changes cannot be observed out of order. Cells only exist when a FIFO is instantiated.
# The wildcards below match every axis_async_fifo instance in the design; the two periods
# (12.5 ns / 10.0 ns) are sized for THIS plan's 80 MHz <-> 100 MHz IQ FIFO only. A second
# FIFO instantiated between a different pair of clocks needs its own scoped set_max_delay
# (narrow the -hier filter to that instance's path, with that FIFO's own clock periods).
set fifo_wr_ptr [get_cells -quiet -hier -filter {NAME =~ *wr_gray_reg*}]
set fifo_rd_ptr [get_cells -quiet -hier -filter {NAME =~ *rd_gray_reg*}]
set wr2rd_sync  [get_cells -quiet -hier -filter {NAME =~ *u_wr2rd*stage_reg*}]
set rd2wr_sync  [get_cells -quiet -hier -filter {NAME =~ *u_rd2wr*stage_reg*}]
if {[llength $fifo_wr_ptr] > 0 && [llength $wr2rd_sync] > 0} { set_max_delay -datapath_only -from $fifo_wr_ptr -to $wr2rd_sync 12.500 }
if {[llength $fifo_rd_ptr] > 0 && [llength $rd2wr_sync] > 0} { set_max_delay -datapath_only -from $fifo_rd_ptr -to $rd2wr_sync 10.000 }

# All cdc_sync/cdc_pulse/rst_sync first-stage flops are ASYNC_REG. Post-synthesis, confirm the
# attribute survived on these unpacked-array registers with:
#   report_property [get_cells -hier -filter {NAME =~ *stage_reg*}] ASYNC_REG
