#!/usr/bin/env python3
"""Generate mem/st7789_init.mem — the ST7789V initialisation ROM for st7789_ctrl.

Word format (16 bit): [15:14] type: 0=command byte, 1=data byte, 2=delay (ticks in [13:0]), 3=end.
Values follow the ST7789V datasheet (V1.0 2013/10): SWRESET p.160, SLPOUT p.181, COLMOD p.221,
MADCTL p.212, PORCTRL p.260, GCTRL p.263, VCOMS p.266, LCMCTRL p.268, VDVVRHEN p.270, VRHS p.271,
VDVS p.273, FRCTRL2 p.277, PWCTRL1 p.283, PVGAMCTRL/NVGAMCTRL p.287/289, CASET p.195, RASET p.197.
"""
import pathlib

ROM_DEPTH = 128
WIDTH, HEIGHT = 320, 240          # landscape (MADCTL.MV = 1)
MADCTL = 0x60                     # MV=1, MX=1, RGB order. Alternative orientation: 0xA0 (MV|MY)
INVERT = True                     # most IPS ST7789V modules need INVON for correct colours

T_CMD, T_DATA, T_DELAY, T_END = 0, 1, 2, 3

def cmd(c):        return [(T_CMD << 14) | (c & 0xFF)]
def data(*bs):     return [(T_DATA << 14) | (b & 0xFF) for b in bs]
def delay(ticks):  return [(T_DELAY << 14) | (ticks & 0x3FFF)]
def end():         return [(T_END << 14)]

def build_rom():
    w = []
    w += cmd(0x01) + delay(150)                      # SWRESET, wait (>=5 ms; 150 covers sleep-in case)
    w += cmd(0x11) + delay(120)                      # SLPOUT, wait 120 ms
    w += cmd(0x3A) + data(0x55)                      # COLMOD: 65K RGB-IF, 16 bpp MCU (datasheet note: 55h for writes)
    w += cmd(0x36) + data(MADCTL)                    # MADCTL
    w += cmd(0xB2) + data(0x0C, 0x0C, 0x00, 0x33, 0x33)   # PORCTRL
    w += cmd(0xB7) + data(0x35)                      # GCTRL  VGH 13.26 V / VGL -10.43 V
    w += cmd(0xBB) + data(0x20)                      # VCOMS 0.90 V (panel dependent)
    w += cmd(0xC0) + data(0x2C)                      # LCMCTRL
    w += cmd(0xC2) + data(0x01, 0xFF)                # VDVVRHEN
    w += cmd(0xC3) + data(0x0B)                      # VRHS
    w += cmd(0xC4) + data(0x20)                      # VDVS 0 V
    w += cmd(0xC6) + data(0x0F)                      # FRCTRL2 60 Hz dot inversion
    w += cmd(0xD0) + data(0xA4, 0xA1)                # PWCTRL1
    gamma = (0x70, 0x2C, 0x2E, 0x15, 0x10, 0x09, 0x48, 0x33, 0x53, 0x0B, 0x19, 0x18, 0x20, 0x25)
    w += cmd(0xE0) + data(*gamma)                    # PVGAMCTRL (datasheet defaults)
    w += cmd(0xE1) + data(*gamma)                    # NVGAMCTRL
    if INVERT:
        w += cmd(0x21)                               # INVON
    w += cmd(0x13) + delay(10)                       # NORON
    w += cmd(0x29) + delay(10)                       # DISPON
    w += cmd(0x2A) + data(0x00, 0x00, (WIDTH - 1) >> 8, (WIDTH - 1) & 0xFF)    # CASET
    w += cmd(0x2B) + data(0x00, 0x00, (HEIGHT - 1) >> 8, (HEIGHT - 1) & 0xFF)  # RASET
    w += end()
    assert len(w) <= ROM_DEPTH, f"ROM too long: {len(w)}"
    return w

def format_mem(words):
    lines = [f"// ST7789V init ROM, {len(words)} used of {ROM_DEPTH} words. Generated by tools/gen_st7789_rom.py",
             "// [15:14]: 0=cmd 1=data 2=delay(ticks) 3=end"]
    padded = words + [0xC000] * (ROM_DEPTH - len(words))
    lines += [f"{x:04X}" for x in padded]
    return "\n".join(lines) + "\n"

if __name__ == "__main__":
    out = pathlib.Path(__file__).resolve().parents[1] / "mem" / "st7789_init.mem"
    out.write_text(format_mem(build_rom()))
    print(f"wrote {out}")
